swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /unit/:
    get:
      tags:
      - unit
      description: get top100 Unit
      operationId: UnitController.Get100
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Unit'
    post:
      tags:
      - unit
      description: create Unit
      operationId: UnitController.CreateUser
      parameters:
      - in: body
        name: body
        description: body for unit content
        required: true
        schema:
          $ref: '#/definitions/models.Unit'
      responses:
        "200":
          description: '{int} models.Unit.Id'
        "403":
          description: body is empty
  /unit/{id}:
    get:
      tags:
      - unit
      description: get unit by id
      operationId: UnitController.Get
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Unit'
        "403":
          description: :id is empty
definitions:
  models.Object:
    title: Object
    type: object
    properties:
      ObjectId:
        type: string
      PlayerName:
        type: string
      Score:
        type: integer
        format: int64
  models.Profile:
    title: Profile
    type: object
    properties:
      Address:
        type: string
      Age:
        type: integer
        format: int64
      Email:
        type: string
      Gender:
        type: string
  models.Unit:
    title: Unit
    type: object
    properties:
      Key:
        type: string
      KeySize:
        type: integer
        format: int64
      Value:
        type: string
      ValueSize:
        type: integer
        format: int64
  models.User:
    title: User
    type: object
    properties:
      Id:
        type: string
      Password:
        type: string
      Profile:
        $ref: '#/definitions/models.Profile'
      Username:
        type: string
tags:
- name: unit
  description: |
    Operations about Unit
